#%RAML 0.8

title: Charging API
mediaType: application/json

/cards:
  /{cid}:
    get:
      description: as a user or admin, I can get user information
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties":{
                  "uri": {
                    "type": "string"
                    },
                  "id": {
                    "type": "string"
                    },
                  "number": {
                    "type": "string"
                    },
                  "location": {
                    "type": "string"
                    },
                  "balance": {
                    "type": "object",
                    "properties": {
                      "amount": {
                        "type": "number"
                        },
                      "freeCallDuration": {
                        "type": "number"
                        },
                      "freeData": {
                        "type": "number"
                        },
                      "freeSMS": {
                        "type": "number"
                        },
                      "required": ["amount", "freeCallDuration", "freeData", "freeSMS"]
                      }
                    },
                  "required": ["uri", "id", "number", "location", "balance"]
                  }
                }
        404:
    /plans:
      get:
        description: as a user or admin, I can get plan list of a user
        responses:
          200:
            body:
              application/json:
                schema: |
                  {
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "uri":{
                          "type": "string"
                          },
                        "id":{
                          "type": "string"
                          },
                        "name":{
                          "type": "string"
                          },
                        "price":{
                          "type": "number"
                          },
                        "date":{
                          "type": "number"
                          },
                        "timeLimit":{
                          "type": "number"
                          },
                        "required": ["uri", "id", "name", "price", "date", "timeLimit"]
                        }
                      }
                  }
          404:
      /{pid}:
        get:
          description: as a user or admin, I can get product order detail of a user
          responses:
            200:
              body:
                application/json:
                  schema: |
                    {
                      "$schema": "http://json-schema.org/draft-04/schema#",
                      "type": "object",
                      "properties": {
                        "uri":{
                          "type": "string"
                          },
                        "id":{
                          "type": "string"
                          },
                        "name":{
                          "type": "string"
                          },
                        "price":{
                          "type": "number"
                          },
                        "date":{
                          "type": "number"
                          },
                        "timeLimit":{
                          "type": "number"
                          },
                        "freeCallDuration":{
                          "type": "number"
                          },
                        "freeData": {
                          "type": "number"
                          },
                        "freeSMS": {
                          "type": "number"
                        },
                        "callPrice":{
                          "type": "number"
                          },
                        "dataPrice": {
                          "type": "number"
                          },
                        "SMSPrice": {
                          "type": "number"
                          },
                        "required": ["uri", "id", "name", "price", "date", "timeLimit", "freeCallDuration", "freeData", "freeSMS", "callPrice", "dataPrice", "SMSPrice"]
                        }
                    }
            404:
        /plan-payment:
          post:
            description:
            responses:
              201:
              400:
              404:      
    /recharges:
      get:
        description: as a user or admin, I can get recharge list of a user
        responses:
          200:
            body:
              application/json:
                schema: |
                  {
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "uri": {
                          "type": "string"
                          },
                        "id":{
                          "type": "string"
                          },
                        "amount":{
                          "type": "number"
                          },
                        "date": {
                          "type": "number"
                          },
                        "required": ["uri", "id", "amount", "date"]
                        }
                      }
                  }
          404:
      post:
        description: as a user, I can create a recharge
        body:
          application/json:
            schema: |
              {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "amount":{
                  "type": "number"
                  },
                "date": {
                  "type": "number"
                  },
                "required": ["amount", "date"]
                }
              }
        responses:
          201:
            headers:
              Location:
                description: "create recharge uri"
                type: string
          404:
          400:
      /{rid}:
        get:
          description: as a user or admin, I can get recharge detail of a user
          responses:
            200:
              body:
                application/json:
                  schema: |
                    {
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "type": "object",
                    "properties": {
                      "uri": {
                        "type": "string"
                        },
                      "id":{
                        "type": "string"
                        },
                      "amount":{
                        "type": "number"
                        },
                      "date": {
                        "type": "number"
                        },
                      "required": ["uri", "id", "amount", "date"]
                      }
                    }
            404:
    /consumption-records:
      get:
        description: as a user or admin, I can get consumption record list of a user
        responses:
          200:
            body:
              application/json:
                schema: |
                  {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "type": "array",
                  "itmes":{
                    "type": "object",
                    "properties": {
                      "uri": {
                        "type": "string"
                        },
                      "id": {
                        "type": "string"
                        },
                      "consumption_type": {
                        "enum": ["CALL", "DATA", "SMS"]
                        },
                      "date":{
                        "type": "number"
                        },
                      "required": ["uri", "id", "consumption_type", "date"]
                      }
                    }
                  }
          404:
      /{cid}:
        get:
          description: as a user or admin, I can get consumption recored detail
          responses:
            200:
              body:
                application/json:
                  schema: |
                    {
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "enum": [{
                      "type": "object",
                      "properties": {
                        "uri":{
                          "type": "string"
                          },
                        "id": {
                          "type": "string"
                          },
                        "consumption_type": {
                          "enum": ["CALL"]
                          },
                        "number": {
                          "type": "string"
                          },
                        "duration": {
                          "type": "number"
                          },
                        "date": {
                          "type": "number"
                          },
                        "required": ["uri", "id","consumption_type", "number", "duration", "date"]
                        }
                    },
                    {
                    "type": "object",
                    "properties": {
                      "uri":{
                        "type": "string"
                        },
                      "id": {
                        "type": "string"
                        },
                      "consumption_type": {
                        "enum": ["DATA"]
                        },
                      "target_uri": {
                        "type": "string"
                        },
                      "voulume": {
                        "type": "number"
                        },
                      "date": {
                        "type": "number"
                        },
                      "required": ["uri", "id","consumption_type", "target_uri", "voulume", "date"]
                      }
                    },
                    {
                    "type": "object",
                    "properties": {
                      "uri":{
                        "type": "string"
                        },
                      "id": {
                        "type": "string"
                        },
                      "consumption_type": {
                        "enum": ["SMS"]
                        },
                      "target_uri": {
                        "type": "string"
                        },
                      "number": {
                        "type": "number"
                        },
                      "date": {
                        "type": "number"
                        },
                      "required": ["uri", "id","consumption_type", "target_uri", "number", "date"]
                      }
                    }]
                    }
            404:
      /call-records:
        get:
          description: as admin or user, I can get call-record list
          responses:
            200:
              body:
                application/json:
                   schema: |
                    {
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "type": "array",
                    "items":{
                      "uri":{},
                      "id":{},
                      "duration":{},
                      "numbers":{},
                      "date":{},
                      "balancePrice":{}
                    }
                    }
            404:
        post:
          description: as a user, I can create a call record
          body:
          responses:
            201:
              headers:
                Location:
                  type: string
            400:
            404:
      /data-records:
        get:
          description: as admin or user, I can get call-record list
          responses:
            200:
              body:
                application/json:
                   schema: |
                    {
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "type": "array",
                    "items":{
                      "uri":{},
                      "id":{},
                      "voulume":{},
                      "date":{},
                      "balancePrice":{}
                    }
                    }
            404:
        post:
          description: as a user, I can create a data record
          body:
          responses:
            201:
              headers:
                Location:
                  type: string
            400:
            403:
      /SMS-records:
        get:
          description: as admin or user, I can get call-record list
          responses:
            200:
              body:
                application/json:
                   schema: |
                    {
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "type": "array",
                    "items":{
                      "uri":{},
                      "id":{},
                      "number":{},
                      "date":{},
                      "balancePrice":{}
                    }
                    }
            404:
        post:
          description: as a user, I can create a call record
          body:
          responses:
            201:
              headers:
                Location:
                  type: string
            400:
            403:

