#%RAML 0.8

title: Charging API
mediaType: application/json

/products:
  get:
/users:
  /{uid}:
    get:
    /products:
      post:
      /{productId}:
        get:
    /topups:
      post:
      get:
      /{topupId}:
        get:
    /accountRecords:
      post:
      get:
      /{accountRecordId}:
        get:
    /consumptionRecords:
      get:
      /{consumptionRecordId}:
        get:
      /callRecords:
        post:
      /dataRecords:
        post:
      /smsRecords:
        post:
    /shutdownrecords:
      post:
      get:
      /{shutdownRecordsId}:
        get:
