#%RAML 0.8

title: CreditCar Repayment API
mediaType: application/json

/users:
  get:
    description:
    responses:
      200:
      403:
  /{user_id}:
    get:
      description:
      responses:
        200:
        403:
        404:
    post:
      description:
      responses:
        200:
        403:
        400:
        404:
    /session:
      post:
        description:
        responses:
          201:
          400:
      delete:
        description:
        responses:
          200:
          403:
    /cards:
      get:
       description:
       responses:
         200:
         403:
      /{card_id}:
        get:
          description:
          responses:
            200:
            403:
            404:
        /statements:
          /{statement_id}:
            get:
              description:
              responses:
                200:
                403:
                404:
            /repayments:
              get:
                description:
                responses:
                  200:
                  403:
              post:
                description:
                responses:
                  200:
                  400:
                  403:
              /{repayment_id}:
                get:
                  description:
                  responses:
                    200:
                    403:
                    404:
            /instalment-application:
              get:
                description:
                responses:
                  200:
                  403:
                  404:
              post:
                description:
                responses:
                  201:
                  400:
                  403:
            /overdue-record:
              get:
                description:
                responses:
                  200:
                  403:
                  400:
              post:
                description:
                responses:
                  201:
                  400:
                  403:
    /consumptions:
      get:
        description:
        responses:
          200:
          403:
      post:
        description:
        responses:
          201:
          400:
          403:
      /{consumption_id}:
        get:
          description:
          responses:
            200:
            404:
            403:
