#%RAML 0.8

title: Advertisement API
mediaType: application/json

/users:
 /{uid}:
  /contracts:
    get:
      responses:
        200:
        403:
    post:
      responses:
        201:
        400:
        403:
    /{cid}:
      get:
        responses:
          200:
          404:
          403:
      /bills:
        get:
          responses:
            200:
            403:
        post:
          responses:
            201:
            400:
            403:
        /{bid}:
          get:
            responses:
              200:
              404:
              403:
          /payment:
            get:
              responses:
                200:
                404:
                403:
            post:
              responses:
                201:
                400:
                403:
          /commission:
            get:
              responses:
                200:
                404:
                403:
            post:
              responses:
                201:
                400:
